name = "social-sync"
compatibility_date = "2024-01-15"

# Pages configuration
[env.production]
compatibility_date = "2024-01-15"

# Environment variables (these will be set via Cloudflare dashboard or CLI)
# Do not put actual values here - use 'wrangler secret put' command instead
[vars]
# Non-sensitive configuration variables can go here if needed

# Build configuration for Pages
[[pages_build_output_dir]]
# Cloudflare Pages will automatically detect and serve static files from root directory

# Functions configuration is handled automatically by Cloudflare Pages
# Functions in /functions directory are automatically deployed

# Routes configuration (optional - Pages handles this automatically)
# [routes]
# pattern = "*"
# zone_name = "your-domain.com"  # Replace with your actual domain when ready

# KV namespace bindings (if needed in the future)
# [[kv_namespaces]]
# binding = "SOCIAL_SYNC_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# R2 bucket bindings (if needed for file storage in the future)
# [[r2_buckets]]
# binding = "SOCIAL_SYNC_BUCKET"
# bucket_name = "your-bucket-name"

# Analytics (optional)
[analytics]
enabled = true